# Assignment

In [1]:
import numpy as np

## Q1. Create a 3x3x3 array with random values.

In [2]:
# Ans1.
x = np.random.random((3,3,3))
print('3x3x3 Array: ')
print(x)
print('Shape:',x.shape)

3x3x3 Array: 
[[[0.42993632 0.29846651 0.4891575 ]
  [0.15273436 0.51313899 0.51711861]
  [0.56063497 0.55695265 0.56932113]]

 [[0.90508325 0.73717044 0.51324116]
  [0.77009187 0.91052899 0.59619072]
  [0.47507347 0.24384775 0.50941899]]

 [[0.60483692 0.734929   0.80811085]
  [0.13515376 0.7307454  0.90695859]
  [0.44890579 0.80606887 0.82924609]]]
Shape: (3, 3, 3)


## Q2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [3]:
# Ans2. 
y = np.zeros((5,5))
for i in range(len(y)):
    for j in range(len(y)):
        if(i==j+1):
            y[i][j]=i
print(y)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Q3. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
# Ans3. 
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q4. Normalize a 5x5 random matrix.

In [5]:
# Ans4.
a = np.random.randn(5,5)
print("Before:\n")
print(a)

amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)

print("\nAfter:\n")
print(a)

Before:

[[-0.47034127  0.95576896  1.21326741  0.42822577  0.94991588]
 [ 0.40569079 -0.3110939  -0.86126903  0.18169349  0.43825749]
 [ 1.62830629  1.76072151 -1.52441537 -0.23450783  0.33246948]
 [-0.14602203  0.27372682  0.28612665 -0.38444361 -0.11157757]
 [-0.59044917  0.51158147 -0.80248943 -0.00421977  1.10901153]]

After:

[[0.32086155 0.75497138 0.83335425 0.59438654 0.7531897 ]
 [0.58752686 0.36933666 0.20186262 0.51934179 0.59744021]
 [0.95969263 1.         0.         0.39264956 0.5652382 ]
 [0.41958475 0.54735686 0.55113138 0.34700891 0.43006969]
 [0.28430054 0.61976012 0.21975521 0.46274955 0.80161862]]


## Q5. How to find common values between two arrays?

In [6]:
# Ans5.
a1 = np.array([1,5,7,9,8,5])
a2 = [6,9,7,9,5]
print("Array 1: ", a1)
print("Array 2: ", a2)
print("Common values between two arrays:", np.intersect1d(a1, a2))

Array 1:  [1 5 7 9 8 5]
Array 2:  [6, 9, 7, 9, 5]
Common values between two arrays: [5 7 9]


## Q6. How to get the dates of yesterday, today and tomorrow?

In [7]:
#Ans6.
import datetime as dt
today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2021-06-09
Today:  2021-06-10
Tomorrow:  2021-06-11


## Q7. Consider two random array A and B, check if they are equal.

In [8]:
# Ans7.
a = np.array([5,3,1,4,2])
b =  np.array([1,2,3,4,5])
print('Array 1:\n', a)
print('Array 2:\n', b)
print('True if two arrays are equal')
print('False if two arrays are equal')
np.array_equal(a,b)

Array 1:
 [5 3 1 4 2]
Array 2:
 [1 2 3 4 5]
True if two arrays are equal
False if two arrays are equal


False

## Q8. Create random vector of size 10 and replace the maximum value by 0.

In [9]:
# Ans8.
v = np.random.randn(10,1)
print('Random Vector: ')
print(v)
max_val = np.amax(v)
print('Maximum Value in the vector is: ',max_val)
loc = np.where(v==max_val)
v[loc] = 0
print('Updated vector is: ')
print(v)

Random Vector: 
[[-1.95441988]
 [-0.00593068]
 [-0.48614536]
 [-1.0345136 ]
 [ 0.61874869]
 [ 1.58516453]
 [-0.85720418]
 [ 0.89350663]
 [ 0.21533354]
 [-0.74104771]]
Maximum Value in the vector is:  1.5851645337942502
Updated vector is: 
[[-1.95441988]
 [-0.00593068]
 [-0.48614536]
 [-1.0345136 ]
 [ 0.61874869]
 [ 0.        ]
 [-0.85720418]
 [ 0.89350663]
 [ 0.21533354]
 [-0.74104771]]


## Q9. How to print all the values of an array?

In [10]:
#Ans9.
d = np.random.randn(3,3)
print("The array is:")
print(d)
for i in range(len(d)):
    for j in range(len(d)):
        print("The value at index(",i,",",j,")is:",d[i][j])

The array is:
[[ 0.03113876  0.15148372  0.38581629]
 [ 0.63376208 -0.15183098 -1.32605903]
 [-0.94756558 -1.02043017  0.14486576]]
The value at index( 0 , 0 )is: 0.031138761662818315
The value at index( 0 , 1 )is: 0.1514837157696349
The value at index( 0 , 2 )is: 0.3858162882555461
The value at index( 1 , 0 )is: 0.6337620840607663
The value at index( 1 , 1 )is: -0.15183097894648515
The value at index( 1 , 2 )is: -1.326059033018335
The value at index( 2 , 0 )is: -0.947565577968761
The value at index( 2 , 1 )is: -1.020430170044196
The value at index( 2 , 2 )is: 0.14486576095798426


## Q10. Subtract the mean of each row of a matrix.

In [11]:
# Ans10.
arr = np.random.randn(3,3)
print("Initially:")
print(arr)
print("The mean value of each row is:")
arr1=np.mean(arr,axis=1)
print(arr1)
arr2=arr-arr1
print("Matrix after mean is subtracted")
print(arr2)

Initially:
[[ 0.70865915  0.53454288  0.34052945]
 [-1.32262297  2.17568715 -0.33388515]
 [-0.70261386 -1.65713894  1.11208401]]
The mean value of each row is:
[ 0.5279105   0.17305968 -0.4158896 ]
Matrix after mean is subtracted
[[ 0.18074866  0.36148321  0.75641905]
 [-1.85053347  2.00262747  0.08200445]
 [-1.23052436 -1.83019862  1.52797361]]


## Q11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
# Ans11.
k = np.random.rand(5)
print("Initial Vector:\n",k)
i = np.random.randint(0, len(k),5)
print("Random Values:\n",i)
k += np.bincount(i, minlength=len(k))
print("Resultant Vector:\n",k)

Initial Vector:
 [0.90321485 0.61085112 0.47491989 0.2467867  0.37036007]
Random Values:
 [0 1 1 0 2]
Resultant Vector:
 [2.90321485 2.61085112 1.47491989 0.2467867  0.37036007]


## Q12. How to get the diagonal of a dot product?

In [13]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print("Array A:\n", A)
print("\nArray B:\n", B)
print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nDiagonal Elements are:\n', dot)

Array A:
 [[6 8 8]
 [0 4 3]
 [2 7 8]]

Array B:
 [[3 9 3]
 [0 1 2]
 [2 3 0]]

Dot product:
 [[34 86 34]
 [ 6 13  8]
 [22 49 20]]

Diagonal Elements are:
 [34 13 20]


## Q13. How to find the most frequent value in an array?

In [14]:
# Ans13.
g = np.random.randint(0,10,15)
print(g)
print('Most frequent value: ',np.bincount(g).argmax())

[7 7 1 0 6 2 0 1 6 4 1 6 2 5 2]
Most frequent value:  1


## Q14. How to get the n largest values of an array?

In [15]:
# Ans14.
s = np.arange(100)
np.random.shuffle(s)
n = int(input('Enter the value of n: '))
print (s[np.argpartition(-s,n)[:n]])

Enter the value of n: 5
[99 97 98 96 95]


## Q15. How to create a record array from a regular array?

In [16]:
# Ans15.
x1 = np.array(['T','A','V','I','S','H'])
x2 = np.array([1,2,3,4,5,6])

print('Regular Array 1:',x1)
print('Regular Array 2:',x2)

records = np.core.records.fromarrays([x1,x2], names='Col1, Col2') # The arrays are now transposed 

print('\nRecorded Array:', records)

Regular Array 1: ['T' 'A' 'V' 'I' 'S' 'H']
Regular Array 2: [1 2 3 4 5 6]

Recorded Array: [('T', 1) ('A', 2) ('V', 3) ('I', 4) ('S', 5) ('H', 6)]
